### ISSUE TITLE
Spanning commentary refs insert blank verses. 

### ISSUE THREAD

**Issue by EliezerIsrael** [shelfgot/SefariaAddOn-Google#24]
If I insert a spanning Rashi reference, even nodes that have no Hebrew or English are inserted.  

Example: Rashi on Genesis 45:5-10

The API will be returning these verses as empty Arrays [].  It could be that you can just test for the truthiness of each verse before adding it to the sheet.

**Comment by shelfgot** [comment]
Fun to see 14-year-old me learn the concept of truthiness from the eminent R' L.E. Israel. this has been fixed (for a while now!)
