### ISSUE TITLE
Feature Request: select vowelization (none, vowels, simanim)

### ISSUE THREAD

**Issue by mikeage** [shelfgot/SefariaAddOn-Google#31]
I don't know if you're still working on this; I just discovered it today, and love it. Is there any possibility to add  a selector to choose the vowelization used when inserting sources? Especially for Tanach, this would be quite useful. (I may try to do this myself -- never done anything with a Google extension, but the API should be simple enough, if I can figure out a dev environment)

**Comment by shelfgot** [comment]
great minds think alike. Fixed in the new release, which should be pushed to Github in the next day or so and hopefully production ready within the week (if Google's auth process goes smoothly)
