### ISSUE TITLE
Kri U'Ktiv not rendered properly when inserting a source

### ISSUE THREAD

**Issue by mikeage** [shelfgot/SefariaAddOn-Google#32]
E.g.,

```
<span class="mam-kq"><span class="mam-kq-k">(לעבדיך) <span class="mam-kq-q">[לְעַבְדָ֖ךְ]
```
These spans should be stripped out (this is from Daniel 2:4, but it happens everywhere)

**Comment by mikeage** [comment]
(I'm using this again this summer, and saw it's still an issue. I've been doing a search and replace to remove all regexes matching `<span class="mam-[-a-z]*">` but it'd be nice if they weren't there in the first place

**Comment by shelfgot** [comment]
Fixed in the new release (hopefully coming out in the next week!)
